
path:
  schema_prediction: 'schema_prediction.json'
  schema_training: 'schema_training.json'
  trainingFiles: 'training_data'
  validData: 'TrainingDataSet/validTrainingData'
  invalidData: 'TrainingDataSet/invalidTrainingData'
  nullValuesData: 'TrainingDataSet/NullRemovalFiles'
  inputs: './InputFile'

port: 5000

dbconnect:
  database_name: 'Activity'
  table_name: 'activity_recognition'
  host: 'localhost'
  user: 'root'
  password: 'root'




